import {
  compileLinearGradient,
  generateScaleFromAnchor,
  getScaleStepHex,
  getWcagLevel,
} from "@/lib/colorScale";
import type {
  BorderRadiusToken,
  ColorGradient,
  ColorToken,
  DemoDesignSystem,
  DesignToken,
  MotionToken,
  ShadowToken,
  SpacingToken,
  TypographyToken,
} from "@/types/tokens";

const PRIMARY_HEX = "#7733FF";
const PRIMARY_SCALE = generateScaleFromAnchor(PRIMARY_HEX);
const PRIMARY_500 = getScaleStepHex(PRIMARY_SCALE, 500) ?? PRIMARY_HEX;
const PRIMARY_600 = getScaleStepHex(PRIMARY_SCALE, 600) ?? PRIMARY_HEX;

/** Brand: primary 500 → 600. Cool: no secondary yet → primary 500/600 @ 50%. */
const GRADIENT_BRAND: ColorGradient = {
  angle: 135,
  from: { color: PRIMARY_500, opacity: 100 },
  to: { color: PRIMARY_600, opacity: 100 },
};

const GRADIENT_COOL: ColorGradient = {
  angle: 120,
  from: { color: PRIMARY_500, opacity: 50 },
  to: { color: PRIMARY_600, opacity: 50 },
};

export const DEMO_COLOR_TOKENS: ColorToken[] = [
  {
    id: "primary",
    name: "color.primary",
    value: PRIMARY_HEX,
    alias: "brand.500",
    wcag: getWcagLevel(PRIMARY_HEX),
    group: "semantic",
    usedBy: ["button.primary", "link.default"],
    scale: PRIMARY_SCALE,
  },
  {
    id: "primary-hover",
    name: "color.primary.hover",
    value: getScaleStepHex(PRIMARY_SCALE, 600) ?? PRIMARY_HEX,
    alias: "brand.600",
    wcag: getWcagLevel(getScaleStepHex(PRIMARY_SCALE, 600) ?? PRIMARY_HEX),
    group: "semantic",
    usedBy: ["button.primary.hover"],
    stepRef: 600,
    scaleOf: "primary",
  },
  {
    id: "primary-subtle",
    name: "color.primary.subtle",
    value: getScaleStepHex(PRIMARY_SCALE, 50) ?? PRIMARY_HEX,
    alias: "brand.50",
    wcag: getWcagLevel(getScaleStepHex(PRIMARY_SCALE, 50) ?? PRIMARY_HEX),
    group: "semantic",
    usedBy: ["badge.primary"],
    stepRef: 50,
    scaleOf: "primary",
  },
  {
    id: "success",
    name: "color.success",
    value: "#10b981",
    alias: "green.500",
    wcag: "aa",
    group: "feedback",
    usedBy: ["badge.success", "alert.success"],
  },
  {
    id: "warning",
    name: "color.warning",
    value: "#f59e0b",
    alias: "amber.500",
    wcag: "fail",
    group: "feedback",
    usedBy: ["badge.warning"],
  },
  {
    id: "danger",
    name: "color.danger",
    value: "#ef4444",
    alias: "red.500",
    wcag: "aa",
    group: "feedback",
    usedBy: ["badge.error", "input.error"],
  },
  {
    id: "info",
    name: "color.info",
    value: "#3b82f6",
    alias: "blue.500",
    wcag: "aa",
    group: "feedback",
    usedBy: ["badge.info"],
  },
  {
    id: "gradient-brand",
    name: "color.gradient.brand",
    value: compileLinearGradient(GRADIENT_BRAND),
    alias: "gradient.brand",
    wcag: getWcagLevel(GRADIENT_BRAND.from.color),
    group: "semantic",
    usedBy: ["hero.bg", "cta.bg"],
    gradient: GRADIENT_BRAND,
  },
  {
    id: "gradient-cool",
    name: "color.gradient.cool",
    value: compileLinearGradient(GRADIENT_COOL),
    alias: "gradient.cool",
    wcag: getWcagLevel(GRADIENT_COOL.from.color),
    group: "semantic",
    usedBy: ["banner.bg", "promo.bg"],
    gradient: GRADIENT_COOL,
  },
  {
    id: "bg-primary",
    name: "color.bg.primary",
    value: "#ffffff",
    alias: "white",
    wcag: "aaa",
    group: "surface",
    usedBy: ["card.bg", "modal.bg"],
  },
  {
    id: "bg-secondary",
    name: "color.bg.secondary",
    value: "#f8f8f6",
    alias: "gray.50",
    wcag: "aa",
    group: "surface",
    usedBy: ["page.bg"],
  },
  {
    id: "bg-tertiary",
    name: "color.bg.tertiary",
    value: "#f0efed",
    alias: "gray.100",
    wcag: "aa",
    group: "surface",
    usedBy: ["input.bg"],
  },
  {
    id: "border",
    name: "color.border",
    value: "rgba(0,0,0,0.08)",
    alias: "gray.200",
    wcag: "fail",
    group: "border",
    usedBy: ["card.border", "input.border"],
  },
  {
    id: "text-primary",
    name: "color.text.primary",
    value: "#111110",
    alias: "gray.950",
    wcag: "aaa",
    group: "text",
    usedBy: ["heading", "body"],
  },
  {
    id: "text-secondary",
    name: "color.text.secondary",
    value: "#52524e",
    alias: "gray.700",
    wcag: "aaa",
    group: "text",
    usedBy: ["caption", "label"],
  },
  {
    id: "text-tertiary",
    name: "color.text.tertiary",
    value: "#a0a09a",
    alias: "gray.400",
    wcag: "fail",
    group: "text",
    usedBy: ["placeholder"],
  },
];

export const DEMO_TYPOGRAPHY_TOKENS: TypographyToken[] = [
  {
    id: "font-sans",
    name: "typography.fontFamily.sans",
    value: "Inter, system-ui, -apple-system, sans-serif",
    alias: "font.sans",
    group: "family",
    usedBy: ["body", "button", "input"],
  },
  {
    id: "font-body",
    name: "typography.fontFamily.body",
    value: "Inter, system-ui, -apple-system, sans-serif",
    alias: "font.body",
    group: "family",
    usedBy: ["paragraph", "article"],
    refOf: "font-sans",
  },
  {
    id: "font-serif",
    name: "typography.fontFamily.serif",
    value: "Georgia, 'Times New Roman', serif",
    alias: "font.serif",
    group: "family",
    usedBy: ["blockquote", "editorial"],
  },
  {
    id: "font-mono",
    name: "typography.fontFamily.mono",
    value: "ui-monospace, 'Cascadia Code', monospace",
    alias: "font.mono",
    group: "family",
    usedBy: ["code", "pre"],
  },
  {
    id: "text-xs",
    name: "typography.fontSize.xs",
    value: "12px",
    alias: "text.xs",
    group: "size",
    usedBy: ["caption", "badge"],
  },
  {
    id: "text-sm",
    name: "typography.fontSize.sm",
    value: "14px",
    alias: "text.sm",
    group: "size",
    usedBy: ["label", "helper"],
  },
  {
    id: "text-base",
    name: "typography.fontSize.base",
    value: "16px",
    alias: "text.base",
    group: "size",
    usedBy: ["body"],
  },
  {
    id: "text-lg",
    name: "typography.fontSize.lg",
    value: "20px",
    alias: "text.lg",
    group: "size",
    usedBy: ["h4", "lead"],
  },
  {
    id: "text-xl",
    name: "typography.fontSize.xl",
    value: "24px",
    alias: "text.xl",
    group: "size",
    usedBy: ["h3"],
  },
  {
    id: "text-2xl",
    name: "typography.fontSize.2xl",
    value: "30px",
    alias: "text.2xl",
    group: "size",
    usedBy: ["h2"],
  },
  {
    id: "text-3xl",
    name: "typography.fontSize.3xl",
    value: "36px",
    alias: "text.3xl",
    group: "size",
    usedBy: ["h1"],
  },
  {
    id: "text-5xl",
    name: "typography.fontSize.5xl",
    value: "48px",
    alias: "text.5xl",
    group: "size",
    usedBy: ["display"],
  },
  {
    id: "weight-light",
    name: "typography.fontWeight.light",
    value: "300",
    alias: "font.light",
    group: "weight",
    usedBy: ["caption"],
  },
  {
    id: "weight-regular",
    name: "typography.fontWeight.regular",
    value: "400",
    alias: "font.regular",
    group: "weight",
    usedBy: ["body"],
  },
  {
    id: "weight-medium",
    name: "typography.fontWeight.medium",
    value: "500",
    alias: "font.medium",
    group: "weight",
    usedBy: ["label", "button"],
  },
  {
    id: "weight-semibold",
    name: "typography.fontWeight.semibold",
    value: "600",
    alias: "font.semibold",
    group: "weight",
    usedBy: ["heading"],
  },
  {
    id: "weight-bold",
    name: "typography.fontWeight.bold",
    value: "700",
    alias: "font.bold",
    group: "weight",
    usedBy: ["display", "strong"],
  },
  {
    id: "leading-tight",
    name: "typography.lineHeight.tight",
    value: "1.25",
    alias: "leading.tight",
    group: "lineHeight",
    usedBy: ["heading"],
  },
  {
    id: "leading-normal",
    name: "typography.lineHeight.normal",
    value: "1.5",
    alias: "leading.normal",
    group: "lineHeight",
    usedBy: ["body"],
  },
  {
    id: "leading-relaxed",
    name: "typography.lineHeight.relaxed",
    value: "1.75",
    alias: "leading.relaxed",
    group: "lineHeight",
    usedBy: ["prose", "blockquote"],
  },
  {
    id: "tracking-tight",
    name: "typography.letterSpacing.tight",
    value: "-0.025em",
    alias: "tracking.tight",
    group: "letterSpacing",
    usedBy: ["heading", "display"],
  },
  {
    id: "tracking-normal",
    name: "typography.letterSpacing.normal",
    value: "0em",
    alias: "tracking.normal",
    group: "letterSpacing",
    usedBy: ["body"],
  },
  {
    id: "tracking-wide",
    name: "typography.letterSpacing.wide",
    value: "0.05em",
    alias: "tracking.wide",
    group: "letterSpacing",
    usedBy: ["overline", "badge"],
  },
];

export const DEMO_SPACING_TOKENS: SpacingToken[] = [
  {
    id: "spacing-base",
    name: "spacing.base",
    value: "4px",
    alias: "space.unit",
    group: "base",
    usedBy: ["grid", "scale"],
  },
  {
    id: "space-1",
    name: "spacing.1",
    value: "4px",
    alias: "space.1",
    group: "scale",
    usedBy: ["gap.xs", "padding.xs"],
  },
  {
    id: "space-2",
    name: "spacing.2",
    value: "8px",
    alias: "space.2",
    group: "scale",
    usedBy: ["gap.sm", "padding.sm"],
  },
  {
    id: "space-3",
    name: "spacing.3",
    value: "12px",
    alias: "space.3",
    group: "scale",
    usedBy: ["gap.md"],
  },
  {
    id: "space-4",
    name: "spacing.4",
    value: "16px",
    alias: "space.4",
    group: "scale",
    usedBy: ["padding.md", "margin.md"],
  },
  {
    id: "space-5",
    name: "spacing.5",
    value: "20px",
    alias: "space.5",
    group: "scale",
    usedBy: ["gap.lg"],
  },
  {
    id: "space-6",
    name: "spacing.6",
    value: "24px",
    alias: "space.6",
    group: "scale",
    usedBy: ["padding.lg", "section.gap"],
  },
  {
    id: "space-8",
    name: "spacing.8",
    value: "32px",
    alias: "space.8",
    group: "scale",
    usedBy: ["padding.xl"],
  },
  {
    id: "space-10",
    name: "spacing.10",
    value: "40px",
    alias: "space.10",
    group: "scale",
    usedBy: ["section.padding"],
  },
  {
    id: "space-12",
    name: "spacing.12",
    value: "48px",
    alias: "space.12",
    group: "scale",
    usedBy: ["layout.gutter"],
  },
  {
    id: "space-16",
    name: "spacing.16",
    value: "64px",
    alias: "space.16",
    group: "scale",
    usedBy: ["page.margin"],
  },
];

export const DEMO_BORDER_RADIUS_TOKENS: BorderRadiusToken[] = [
  {
    id: "radius-none",
    name: "borderRadius.none",
    value: "0",
    alias: "radius.none",
    group: "scale",
    usedBy: ["table", "divider"],
  },
  {
    id: "radius-sm",
    name: "borderRadius.sm",
    value: "2px",
    alias: "radius.sm",
    group: "scale",
    usedBy: ["chip"],
  },
  {
    id: "radius-md",
    name: "borderRadius.md",
    value: "4px",
    alias: "radius.md",
    group: "scale",
    usedBy: ["input", "badge"],
  },
  {
    id: "radius-lg",
    name: "borderRadius.lg",
    value: "8px",
    alias: "radius.lg",
    group: "scale",
    usedBy: ["button", "card"],
  },
  {
    id: "radius-xl",
    name: "borderRadius.xl",
    value: "12px",
    alias: "radius.xl",
    group: "scale",
    usedBy: ["modal", "popover"],
  },
  {
    id: "radius-2xl",
    name: "borderRadius.2xl",
    value: "16px",
    alias: "radius.2xl",
    group: "scale",
    usedBy: ["panel"],
  },
  {
    id: "radius-3xl",
    name: "borderRadius.3xl",
    value: "24px",
    alias: "radius.3xl",
    group: "scale",
    usedBy: ["hero.card"],
  },
  {
    id: "radius-full",
    name: "borderRadius.full",
    value: "9999px",
    alias: "radius.full",
    group: "scale",
    usedBy: ["avatar", "pill"],
  },
];

export const DEMO_SHADOW_TOKENS: ShadowToken[] = [
  {
    id: "shadow-none",
    name: "shadow.none",
    value: "none",
    alias: "shadow.none",
    group: "elevation",
    usedBy: ["flat.surface"],
  },
  {
    id: "shadow-sm",
    name: "shadow.sm",
    value: "0 1px 2px 0 rgba(17, 17, 16, 0.05)",
    alias: "shadow.sm",
    group: "elevation",
    usedBy: ["input", "chip"],
  },
  {
    id: "shadow-md",
    name: "shadow.md",
    value: "0 4px 6px -1px rgba(17, 17, 16, 0.08), 0 2px 4px -2px rgba(17, 17, 16, 0.06)",
    alias: "shadow.md",
    group: "elevation",
    usedBy: ["card", "dropdown"],
  },
  {
    id: "shadow-lg",
    name: "shadow.lg",
    value: "0 10px 15px -3px rgba(17, 17, 16, 0.1), 0 4px 6px -4px rgba(17, 17, 16, 0.08)",
    alias: "shadow.lg",
    group: "elevation",
    usedBy: ["popover", "sticky.header"],
  },
  {
    id: "shadow-xl",
    name: "shadow.xl",
    value: "0 20px 25px -5px rgba(17, 17, 16, 0.12), 0 8px 10px -6px rgba(17, 17, 16, 0.08)",
    alias: "shadow.xl",
    group: "elevation",
    usedBy: ["modal"],
  },
  {
    id: "shadow-2xl",
    name: "shadow.2xl",
    value: "0 25px 50px -12px rgba(17, 17, 16, 0.2)",
    alias: "shadow.2xl",
    group: "elevation",
    usedBy: ["drawer", "hero.card"],
  },
  {
    id: "shadow-card",
    name: "shadow.card",
    value:
      "0 4px 6px -1px rgba(17, 17, 16, 0.08), 0 2px 4px -2px rgba(17, 17, 16, 0.06)",
    alias: "shadow.card",
    group: "elevation",
    usedBy: ["card", "surface.raised"],
    refOf: "shadow-md",
  },
];

export const DEMO_MOTION_TOKENS: MotionToken[] = [
  {
    id: "duration-fast",
    name: "motion.duration.fast",
    value: "150ms",
    alias: "duration.fast",
    group: "duration",
    usedBy: ["hover", "focus"],
  },
  {
    id: "duration-normal",
    name: "motion.duration.normal",
    value: "250ms",
    alias: "duration.normal",
    group: "duration",
    usedBy: ["transition.default"],
  },
  {
    id: "duration-slow",
    name: "motion.duration.slow",
    value: "400ms",
    alias: "duration.slow",
    group: "duration",
    usedBy: ["modal", "drawer"],
  },
  {
    id: "duration-slower",
    name: "motion.duration.slower",
    value: "600ms",
    alias: "duration.slower",
    group: "duration",
    usedBy: ["page.transition"],
  },
  {
    id: "easing-linear",
    name: "motion.easing.linear",
    value: "linear",
    alias: "easing.linear",
    group: "easing",
    usedBy: ["progress", "loader"],
  },
  {
    id: "easing-ease",
    name: "motion.easing.ease",
    value: "ease",
    alias: "easing.ease",
    group: "easing",
    usedBy: ["transition.default"],
  },
  {
    id: "easing-ease-in",
    name: "motion.easing.ease-in",
    value: "ease-in",
    alias: "easing.ease-in",
    group: "easing",
    usedBy: ["exit"],
  },
  {
    id: "easing-ease-out",
    name: "motion.easing.ease-out",
    value: "ease-out",
    alias: "easing.ease-out",
    group: "easing",
    usedBy: ["enter"],
  },
  {
    id: "easing-ease-in-out",
    name: "motion.easing.ease-in-out",
    value: "ease-in-out",
    alias: "easing.ease-in-out",
    group: "easing",
    usedBy: ["toggle"],
  },
  {
    id: "easing-spring",
    name: "motion.easing.spring",
    value: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    alias: "easing.spring",
    group: "easing",
    usedBy: ["bounce", "interactive"],
  },
];

/** Component-dimension tokens (comp category) — mock list + toggle sizes. */
export const DEMO_COMPONENT_TOKENS: DesignToken[] = [
  {
    id: "button-height-sm",
    name: "button.height.sm",
    value: "32px",
    alias: "btn.h.sm",
    group: "button",
    usedBy: ["Button sm"],
  },
  {
    id: "button-height-md",
    name: "button.height.md",
    value: "40px",
    alias: "btn.h.md",
    group: "button",
    usedBy: ["Button md"],
  },
  {
    id: "button-height-lg",
    name: "button.height.lg",
    value: "48px",
    alias: "btn.h.lg",
    group: "button",
    usedBy: ["Button lg"],
  },
  {
    id: "input-height",
    name: "input.height",
    value: "40px",
    alias: "input.h",
    group: "input",
    usedBy: ["TextField", "Select"],
  },
  {
    id: "input-padding-x",
    name: "input.padding.x",
    value: "14px",
    alias: "input.px",
    group: "input",
    usedBy: ["TextField", "Select"],
  },
  {
    id: "badge-height",
    name: "badge.height",
    value: "22px",
    alias: "badge.h",
    group: "badge",
    usedBy: ["Badge"],
  },
  {
    id: "badge-font-size",
    name: "badge.font.size",
    value: "11px",
    alias: "badge.fs",
    group: "badge",
    usedBy: ["Badge"],
  },
  {
    id: "avatar-size-sm",
    name: "avatar.size.sm",
    value: "28px",
    alias: "avatar.sm",
    group: "avatar",
    usedBy: ["Avatar"],
  },
  {
    id: "avatar-size-md",
    name: "avatar.size.md",
    value: "36px",
    alias: "avatar.md",
    group: "avatar",
    usedBy: ["Avatar"],
  },
  {
    id: "avatar-size-lg",
    name: "avatar.size.lg",
    value: "48px",
    alias: "avatar.lg",
    group: "avatar",
    usedBy: ["Avatar"],
  },
  {
    id: "card-padding",
    name: "card.padding",
    value: "20px",
    alias: "card.p",
    group: "card",
    usedBy: ["Card"],
  },
  {
    id: "card-radius",
    name: "card.radius",
    value: "12px",
    alias: "card.r",
    group: "card",
    usedBy: ["Card"],
  },
  {
    id: "nav-height",
    name: "nav.height",
    value: "52px",
    alias: "nav.h",
    group: "nav",
    usedBy: ["Navbar"],
  },
  {
    id: "sidebar-width",
    name: "sidebar.width",
    value: "240px",
    alias: "sidebar.w",
    group: "sidebar",
    usedBy: ["Sidebar"],
  },
  {
    id: "toggle-width-sm",
    name: "toggle.width.sm",
    value: "30px",
    alias: "toggle.w.sm",
    group: "toggle",
    usedBy: ["Switch compact"],
  },
  {
    id: "toggle-height-sm",
    name: "toggle.height.sm",
    value: "18px",
    alias: "toggle.h.sm",
    group: "toggle",
    usedBy: ["Switch compact"],
  },
  {
    id: "toggle-width-md",
    name: "toggle.width.md",
    value: "38px",
    alias: "toggle.w.md",
    group: "toggle",
    usedBy: ["Switch"],
  },
  {
    id: "toggle-height-md",
    name: "toggle.height.md",
    value: "22px",
    alias: "toggle.h.md",
    group: "toggle",
    usedBy: ["Switch"],
  },
];

export const demoDesignSystem: DemoDesignSystem = {
  colors: DEMO_COLOR_TOKENS,
  typography: DEMO_TYPOGRAPHY_TOKENS,
  spacing: DEMO_SPACING_TOKENS,
  borderRadius: DEMO_BORDER_RADIUS_TOKENS,
  shadows: DEMO_SHADOW_TOKENS,
  motion: DEMO_MOTION_TOKENS,
};

export const SYSTEM_NAMES: Record<string, string> = {
  "1": "Acme Corp",
  "2": "Startup Kit",
  "3": "Atlas Design",
};
